version: "3.7"

services:
  app_server:
    image: docker-registry.test.etribes.de:5000/shopware-6:latest
    env_file:
      - example.env
    links:
      - app_mysql

  app_mysql:
    image: percona:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

# vim: set shiftwidth=2 tabstop=2 expandtab:
